use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Status of a clarification request in the self-healing pipeline.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ClarificationStatus {
    /// Question generated, waiting for answer.
    Pending,
    /// Answer received, conflict resolved.
    Resolved,
    /// Expired without answer.
    Expired,
    /// Manually dismissed by operator.
    Dismissed,
}

/// A clarification request generated by the self-healing memory system.
///
/// When the conflict radar detects a contradiction between facts, the system
/// generates a targeted question to resolve the ambiguity. When answered
/// (either via ingestion or manual resolution), the system reconciles the
/// conflicting facts.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ClarificationRequest {
    /// Unique ID for this clarification.
    pub id: Uuid,
    /// User whose memory has the conflict.
    pub user_id: Uuid,
    /// The generated clarification question.
    pub question: String,
    /// Current status.
    pub status: ClarificationStatus,
    /// IDs of the conflicting edges that triggered this clarification.
    pub conflict_edge_ids: Vec<Uuid>,
    /// Source entity name involved in the conflict.
    pub source_entity: String,
    /// Relationship label involved in the conflict.
    pub label: String,
    /// The conflicting facts (human-readable).
    pub conflicting_facts: Vec<String>,
    /// Conflict severity score (0.0-1.0) from the conflict radar.
    pub severity: f32,
    /// When this clarification was created.
    pub created_at: DateTime<Utc>,
    /// When this clarification expires (if unanswered).
    pub expires_at: DateTime<Utc>,
    /// When this clarification was resolved (if resolved).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub resolved_at: Option<DateTime<Utc>>,
    /// The answer that resolved this clarification (if resolved).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub resolution_answer: Option<String>,
    /// Edge ID that was kept as the winning fact (if resolved).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub winning_edge_id: Option<Uuid>,
    /// Episode ID that provided the resolution (if via ingestion).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub resolution_episode_id: Option<Uuid>,
}

/// Default clarification TTL in days.
pub const DEFAULT_CLARIFICATION_TTL_DAYS: u32 = 7;

impl ClarificationRequest {
    /// Create a new pending clarification request.
    pub fn new(
        user_id: Uuid,
        question: String,
        conflict_edge_ids: Vec<Uuid>,
        source_entity: String,
        label: String,
        conflicting_facts: Vec<String>,
        severity: f32,
        ttl_days: u32,
    ) -> Self {
        let now = Utc::now();
        Self {
            id: Uuid::now_v7(),
            user_id,
            question,
            status: ClarificationStatus::Pending,
            conflict_edge_ids,
            source_entity,
            label,
            conflicting_facts,
            severity: severity.clamp(0.0, 1.0),
            created_at: now,
            expires_at: now + chrono::Duration::days(ttl_days as i64),
            resolved_at: None,
            resolution_answer: None,
            winning_edge_id: None,
            resolution_episode_id: None,
        }
    }

    /// Check if this clarification has expired.
    pub fn is_expired(&self) -> bool {
        self.status == ClarificationStatus::Pending && Utc::now() > self.expires_at
    }

    /// Resolve this clarification with an answer.
    pub fn resolve(
        &mut self,
        answer: String,
        winning_edge_id: Option<Uuid>,
        resolution_episode_id: Option<Uuid>,
    ) {
        self.status = ClarificationStatus::Resolved;
        self.resolved_at = Some(Utc::now());
        self.resolution_answer = Some(answer);
        self.winning_edge_id = winning_edge_id;
        self.resolution_episode_id = resolution_episode_id;
    }

    /// Dismiss this clarification without resolving.
    pub fn dismiss(&mut self) {
        self.status = ClarificationStatus::Dismissed;
        self.resolved_at = Some(Utc::now());
    }

    /// Mark as expired.
    pub fn expire(&mut self) {
        self.status = ClarificationStatus::Expired;
    }
}

/// Request body for manually resolving a clarification.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ResolveClarificationRequest {
    /// The answer to the clarification question.
    pub answer: String,
    /// Which conflicting edge should be kept (the "winner").
    #[serde(skip_serializing_if = "Option::is_none")]
    pub winning_edge_id: Option<Uuid>,
}

/// Request body for generating clarifications from conflicts.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GenerateClarificationsRequest {
    /// Minimum conflict severity to generate clarifications for (default: 0.6).
    #[serde(default = "default_min_severity")]
    pub min_severity: f32,
    /// Maximum number of clarifications to generate (default: 5).
    #[serde(default = "default_max_clarifications")]
    pub max_clarifications: u32,
}

fn default_min_severity() -> f32 {
    0.6
}
fn default_max_clarifications() -> u32 {
    5
}

impl Default for GenerateClarificationsRequest {
    fn default() -> Self {
        Self {
            min_severity: 0.6,
            max_clarifications: 5,
        }
    }
}

/// Generate a clarification question from conflicting facts.
///
/// This is a pure function that constructs a natural-language question
/// from the conflict metadata. For LLM-generated questions, use
/// `LlmProvider::generate_clarification()`.
pub fn generate_clarification_question(
    source_entity: &str,
    label: &str,
    conflicting_facts: &[String],
) -> String {
    if conflicting_facts.len() == 2 {
        format!(
            "We have conflicting information about {}'s {}. Is it \"{}\" or \"{}\"?",
            source_entity, label, conflicting_facts[0], conflicting_facts[1]
        )
    } else if conflicting_facts.is_empty() {
        format!(
            "Can you clarify the current status of {}'s {}?",
            source_entity, label
        )
    } else {
        let facts_list = conflicting_facts
            .iter()
            .enumerate()
            .map(|(i, f)| format!("{}. \"{}\"", i + 1, f))
            .collect::<Vec<_>>()
            .join(", ");
        format!(
            "We have {} conflicting facts about {}'s {}: {}. Which is current?",
            conflicting_facts.len(),
            source_entity,
            label,
            facts_list
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_clarification_request_new() {
        let req = ClarificationRequest::new(
            Uuid::from_u128(1),
            "Is it still Adidas?".into(),
            vec![Uuid::from_u128(10), Uuid::from_u128(11)],
            "Kendra".into(),
            "loves".into(),
            vec!["loves Adidas".into(), "loves Nike".into()],
            0.85,
            7,
        );
        assert_eq!(req.status, ClarificationStatus::Pending);
        assert_eq!(req.conflict_edge_ids.len(), 2);
        assert!(req.resolved_at.is_none());
        assert!(req.expires_at > req.created_at);
    }

    #[test]
    fn test_clarification_resolve() {
        let mut req = ClarificationRequest::new(
            Uuid::from_u128(1),
            "Which brand?".into(),
            vec![Uuid::from_u128(10)],
            "Kendra".into(),
            "loves".into(),
            vec!["Adidas".into(), "Nike".into()],
            0.8,
            7,
        );
        req.resolve("Nike is correct".into(), Some(Uuid::from_u128(11)), None);
        assert_eq!(req.status, ClarificationStatus::Resolved);
        assert!(req.resolved_at.is_some());
        assert_eq!(req.resolution_answer.as_deref(), Some("Nike is correct"));
        assert_eq!(req.winning_edge_id, Some(Uuid::from_u128(11)));
    }

    #[test]
    fn test_clarification_dismiss() {
        let mut req = ClarificationRequest::new(
            Uuid::from_u128(1),
            "question".into(),
            vec![],
            "entity".into(),
            "label".into(),
            vec![],
            0.5,
            7,
        );
        req.dismiss();
        assert_eq!(req.status, ClarificationStatus::Dismissed);
        assert!(req.resolved_at.is_some());
    }

    #[test]
    fn test_clarification_expire() {
        let mut req = ClarificationRequest::new(
            Uuid::from_u128(1),
            "question".into(),
            vec![],
            "entity".into(),
            "label".into(),
            vec![],
            0.5,
            7,
        );
        req.expire();
        assert_eq!(req.status, ClarificationStatus::Expired);
    }

    #[test]
    fn test_clarification_is_expired() {
        let mut req = ClarificationRequest::new(
            Uuid::from_u128(1),
            "question".into(),
            vec![],
            "entity".into(),
            "label".into(),
            vec![],
            0.5,
            0, // 0 days TTL = expires immediately
        );
        // With TTL=0, expires_at = created_at, so it should be expired
        // (Utc::now() > expires_at since expires_at was set a moment ago)
        assert!(req.is_expired() || req.expires_at >= Utc::now());
        // Force expiration by setting a past time
        req.expires_at = Utc::now() - chrono::Duration::seconds(1);
        assert!(req.is_expired());
    }

    #[test]
    fn test_clarification_is_not_expired_when_resolved() {
        let mut req = ClarificationRequest::new(
            Uuid::from_u128(1),
            "question".into(),
            vec![],
            "entity".into(),
            "label".into(),
            vec![],
            0.5,
            7,
        );
        req.resolve("answer".into(), None, None);
        req.expires_at = Utc::now() - chrono::Duration::days(1); // past expiry
        assert!(
            !req.is_expired(),
            "Resolved clarifications should not be considered expired"
        );
    }

    #[test]
    fn test_clarification_severity_clamped() {
        let req = ClarificationRequest::new(
            Uuid::from_u128(1),
            "q".into(),
            vec![],
            "e".into(),
            "l".into(),
            vec![],
            1.5, // above 1.0
            7,
        );
        assert_eq!(req.severity, 1.0, "Severity should be clamped to 1.0");

        let req2 = ClarificationRequest::new(
            Uuid::from_u128(2),
            "q".into(),
            vec![],
            "e".into(),
            "l".into(),
            vec![],
            -0.5, // below 0.0
            7,
        );
        assert_eq!(req2.severity, 0.0, "Severity should be clamped to 0.0");
    }

    #[test]
    fn test_clarification_status_serde() {
        let statuses = vec![
            ClarificationStatus::Pending,
            ClarificationStatus::Resolved,
            ClarificationStatus::Expired,
            ClarificationStatus::Dismissed,
        ];
        for status in statuses {
            let json = serde_json::to_string(&status).unwrap();
            let back: ClarificationStatus = serde_json::from_str(&json).unwrap();
            assert_eq!(back, status);
        }
    }

    #[test]
    fn test_clarification_serde_roundtrip() {
        let req = ClarificationRequest::new(
            Uuid::from_u128(1),
            "Which brand?".into(),
            vec![Uuid::from_u128(10), Uuid::from_u128(11)],
            "Kendra".into(),
            "loves".into(),
            vec!["Adidas".into(), "Nike".into()],
            0.85,
            7,
        );
        let json = serde_json::to_string(&req).unwrap();
        let back: ClarificationRequest = serde_json::from_str(&json).unwrap();
        assert_eq!(back.id, req.id);
        assert_eq!(back.question, req.question);
        assert_eq!(back.status, ClarificationStatus::Pending);
        assert_eq!(back.conflict_edge_ids.len(), 2);
    }

    #[test]
    fn test_generate_clarification_question_two_facts() {
        let q = generate_clarification_question(
            "Kendra",
            "loves",
            &["Adidas shoes".into(), "Nike shoes".into()],
        );
        assert!(q.contains("Kendra"));
        assert!(q.contains("Adidas"));
        assert!(q.contains("Nike"));
    }

    #[test]
    fn test_generate_clarification_question_empty() {
        let q = generate_clarification_question("Kendra", "loves", &[]);
        assert!(q.contains("Kendra"));
        assert!(q.contains("loves"));
    }

    #[test]
    fn test_generate_clarification_question_many_facts() {
        let q = generate_clarification_question(
            "User",
            "prefers",
            &["A".into(), "B".into(), "C".into()],
        );
        assert!(q.contains("3 conflicting"));
    }

    #[test]
    fn test_resolve_clarification_request_serde() {
        let req = ResolveClarificationRequest {
            answer: "Nike is correct".into(),
            winning_edge_id: Some(Uuid::from_u128(42)),
        };
        let json = serde_json::to_string(&req).unwrap();
        let back: ResolveClarificationRequest = serde_json::from_str(&json).unwrap();
        assert_eq!(back.answer, "Nike is correct");
        assert_eq!(back.winning_edge_id, Some(Uuid::from_u128(42)));
    }

    #[test]
    fn test_generate_clarifications_request_defaults() {
        let req = GenerateClarificationsRequest::default();
        assert_eq!(req.min_severity, 0.6);
        assert_eq!(req.max_clarifications, 5);
    }
}
