//! Sleep-time memory digests.
//!
//! [`MemoryDigest`] captures per-user topic summaries generated during idle
//! windows by the ingestion pipeline's consolidation step. Used for proactive
//! context enrichment and progressive summarization.

use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// A memory digest summarizing a user's long-term knowledge state.
///
/// Generated by the sleep-time compute scheduler (background idle-triggered)
/// or on-demand via `POST /api/v1/memory/:user/digest`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, utoipa::ToSchema)]
pub struct MemoryDigest {
    pub user_id: Uuid,
    pub summary: String,
    pub entity_count: usize,
    pub edge_count: usize,
    pub dominant_topics: Vec<String>,
    pub generated_at: chrono::DateTime<chrono::Utc>,
    /// Which model generated this digest.
    pub model: String,
    /// Coherence score (0.0–1.0) measuring internal consistency of the user's
    /// knowledge graph. Computed by the coherence scoring system.
    /// `None` for digests generated before coherence scoring was available.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub coherence_score: Option<f32>,
}
