{{- if and .Values.mnemo.bootstrapKeys (not .Values.mnemo.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mnemo.fullname" . }}-auth
  labels:
    {{- include "mnemo.labels" . | nindent 4 }}
type: Opaque
stringData:
  MNEMO_AUTH_API_KEYS: {{ .Values.mnemo.bootstrapKeys | quote }}
{{- end }}
---
{{- if and .Values.mnemo.encryptionEnabled .Values.mnemo.encryptionMasterKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mnemo.fullname" . }}-encryption
  labels:
    {{- include "mnemo.labels" . | nindent 4 }}
type: Opaque
stringData:
  MNEMO_ENCRYPTION_MASTER_KEY: {{ .Values.mnemo.encryptionMasterKey | quote }}
{{- end }}
